WHITE_ELO = 700
BLACK_ELO = 700

TERMINAL_BONUS = 50
CASTLING_BONUS = 15

MAX_MOVES_PER_EPISODE = 200
K_FACTOR = 32

SAVED_MODELS_PATH = "/path/to/saved_models"
SAVED_GAMES_PATH = "/path/to/saved_games"
