import os
from dotenv import load_dotenv


load_dotenv()


ACTION_SPACE = 4672

WHITE_ELO = 700
BLACK_ELO = 700

TERMINAL_BONUS = 1.0
CASTLING_BONUS = 0.1

EVAL_SCALING_FACTOR = 50
K_FACTOR = 32

MAX_MOVES_PER_EPISODE = 250

SAVED_MODELS_PATH = os.getenv("SAVED_MODELS_PATH")
SAVED_GAMES_PATH = os.getenv("SAVED_GAMES_PATH")
SAVED_GRAPHS_PATH = os.getenv("SAVED_GRAPHS_PATH")